feat: fetch blockchains from debank
crypkit/blockapi pull request #122
Opened 2023-05-13 11:20 UTC by galvanizze

it's needed for very rare scenario - update icons for blockchains

2023-05-15 13:38 UTC, hanjano requested changes

2023-05-15 13:38 UTC, hanjano commented on setup.py
> +        'requests==2.28.0',
Maybe update requests on line 21

2023-05-16 03:24 UTC, galvanizze commented on setup.py
> +        'requests==2.28.0',
lol I didn't see it 😅

2023-05-16 06:42 UTC, hanjano approved these changes

2023-05-16 08:25 UTC, merged