F v2 extend
crypkit/blockapi pull request #28
Opened 2022-01-05 10:48 UTC by ladovina

Add Covalenthq API + some refactoring.

2022-01-05 11:27 UTC, galvanizze requested changes
mám len pár poznámok, inak fajn PR 👍 :)

2022-01-05 11:27 UTC, galvanizze commented on blockapi/v2/api/covalenth/base.py
> +        self._session.auth = (api_key, "")
nápad: 

`CovalentApiBase` by mohla byť abstract class a mať definovaný `chain_id = None` (btw rovnako ako to máš aj pre `api_options`). Tým pádom by `__init__` nemusel mať argument `chain_id` a mohol by si ho vymazať z každej child classy, ktorá dedí od `CovalentApiBase`.

2022-01-05 11:27 UTC, galvanizze commented on blockapi/v2/api/covalenth/base.py
> +        for raw_balance in raw_balances:
atribút `self.coin` (základná mena blockchainu) som chcel mať na úrovni tých class definovanú, aby sme pre viac rôznych API providerov nemuseli definovať ten coin znovu a aj aby to nemuselo byť vždy definované v kóde.

Covalent to má však trošku iný interface ako ostatné API služby, base balance sa vracia medzi tokenmi, z dokumentácie: "As a special case, network native tokens like ETH on Ethereum are also returned even though it's not a token contract.". Ale i tak by som chcel aby sme vždy ošetrili tento prípad a definovali konštantu `self.coin` s ručne vyplnenými parametrami, mimo iné i `coingecko_id` je pre nás veľmi dôležitá info a zrýchľuje mapovanie v Crypkite.

Tu je príklad base currency (ETH) v response:

![image](https://user-images.githubusercontent.com/19332322/148209503-5766becf-22f3-47de-bf4c-af9978d4904d.png)

2022-01-05 11:27 UTC, galvanizze commented on blockapi/test/e2e/v2/test_covalent.py
> +def test_get_balances(api_class: Type[CovalentApiBase], address: str) -> None:
tento základný get_balance testuje aj generický test; aktuálne tam nie je definovaný ten rate limit, ale radšej by som to doplnil do toho generic testu. čo myslíš?

2022-01-05 11:27 UTC, galvanizze commented on blockapi/test/v2/api/covalenth/test_ethereum.py
> +def test_parse_balance(eth_covalent_api, covalenth_eth_balances_response):
ja na takýto typ testov, keď potrebujem response používam VCR mock, poznáš?

[príklad z v1](https://github.com/crypkit/blockapi/blob/master/blockapi/test/api/test_solana.py#L12)

2022-01-05 11:27 UTC, galvanizze commented on blockapi/v2/api/covalenth/avalanche.py
> +        blockchain=Blockchain.ETHEREUM,
zlý chain

2022-01-05 11:27 UTC, galvanizze commented on blockapi/v2/api/covalenth/polygon.py
> +        blockchain=Blockchain.ETHEREUM,
zlý chain

2022-01-05 11:27 UTC, galvanizze commented on blockapi/v2/base.py
> +    def get_balance(self, *args, **kwargs) -> List[BalanceItem]:
tu môžeš pridať argument `address`, ten je povinný

2022-01-05 11:40 UTC, ladovina commented on blockapi/v2/api/covalenth/base.py
> +        self._session.auth = (api_key, "")
Yes I was thinking about it - but current solution has one big plus: we force child classes to set chain_id which I like.

Currently `api_options` is not forced to be implemented which I do not like - there are ways how to do it even with class attr. but to have it in constructor like `chain_id` is simple which I probably prefer...

2022-01-05 13:03 UTC, ladovina commented on blockapi/v2/api/covalenth/base.py
> +        self._session.auth = (api_key, "")
Changed to abstractmethod + property.

2022-01-06 15:59 UTC, ladovina commented on blockapi/v2/api/covalenth/base.py
> +        for raw_balance in raw_balances:
self.coin added + added skipping of "blockchain-native" coins in "_parse_items".

2022-01-06 16:00 UTC, ladovina commented on blockapi/v2/api/covalenth/avalanche.py
> +        blockchain=Blockchain.ETHEREUM,
fixed

2022-01-06 16:00 UTC, ladovina commented on blockapi/v2/api/covalenth/polygon.py
> +        blockchain=Blockchain.ETHEREUM,
fixed

2022-01-06 16:48 UTC, ladovina commented on blockapi/v2/base.py
> +    def get_balance(self, *args, **kwargs) -> List[BalanceItem]:
I am for strictly define it as `get_balance(self, address:str)` or leave it as it is. 

That means I do not want to mix it to sth like this: `get_balance(self, address, *args, **kwargs)` what do you think?

2022-01-06 16:53 UTC, galvanizze commented on blockapi/v2/base.py
> +    def get_balance(self, *args, **kwargs) -> List[BalanceItem]:
maybe we can include at least `**kwargs` as backdoors for special attributes? Or leave it just with address as you proposed.

2022-01-06 17:04 UTC, ladovina commented on blockapi/test/e2e/v2/test_covalent.py
> +def test_get_balances(api_class: Type[CovalentApiBase], address: str) -> None:
yes I will move it there :+1:

2022-01-07 10:50 UTC, ladovina commented on blockapi/test/v2/test_data.py
> +API_CLASSES = [EthplorerApi, SolanaApi, TerraApi]
added

2022-01-07 10:55 UTC, ladovina commented on blockapi/v2/base.py
> +    def get_balance(self, *args, **kwargs) -> List[BalanceItem]:
changed to strict "get_balance(self, address: str)"

2022-01-07 11:01 UTC, ladovina commented on blockapi/test/v2/api/covalenth/test_ethereum.py
> +def test_parse_balance(eth_covalent_api, covalenth_eth_balances_response):
Ok, I didn't know this.

But if you do not insist on it i would stick to simple json fixture - simplicity, transparent, no 3rd party deps + I want to test only parsing here (no http which is tested in test general).

2022-01-10 09:49 UTC, galvanizze requested changes
very nice, just one thing, thank you :)

2022-01-10 09:49 UTC, galvanizze commented on blockapi/v2/api/covalenth/astar.py
> +        super().__init__(api_key)
if there is no change in `__init__` (comparing to parent), you can omit it in child class

2022-01-10 10:02 UTC, ladovina commented on blockapi/v2/api/covalenth/astar.py
> +        super().__init__(api_key)
good point, I will change it.

2022-01-10 10:19 UTC, ladovina commented on blockapi/v2/api/covalenth/astar.py
> +        super().__init__(api_key)
changed

2022-01-11 09:35 UTC, galvanizze commented on blockapi/test/v2/api/covalenth/test_ethereum.py
> +def test_parse_balance(eth_covalent_api, covalenth_eth_balances_response):
makes sense

2022-01-12 12:31 UTC, merged